version: '3.7'
networks:
  sam-local:
    driver: bridge
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    networks:
      - sam-local
    ports:
      - "8000:8000"